### PR TITLE
Add PlayFab as one of third party apps and its link to terms

### PR DESCRIPTION
**Pull request by harveyjavier**

### CODE REVIEW

**Review by clowreed — APPROVED** [review]
Linked!

**Review by kojiadrianojr — APPROVED** [review]
Aprubado!

**Review by kbaldo — APPROVED** [review]
Redirected!

**Review by EJBarba — APPROVED** [review]
Anadawan!

**Comment by harveyjavier** [comment]
AM nyo na 😄 tinkz

**Pull request merged**
